import { PlaceHolderImages } from "@/lib/placeholder-images";
import type { Post } from "@/lib/types";

export const posts: Post[] = [
  {
    id: "blog-1",
    slug: "getting-started-with-flutter-a-beginners-guide",
    title: "Getting Started with Flutter: A Beginner's Guide",
    description: "Your first steps into cross-platform development. Learn how to set up your environment and create your very first Flutter application.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-1-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-1-thumbnail")!.imageHint,
    date: "July 28, 2024",
    author: "Reyad",
  },
  {
    id: "blog-2",
    slug: "understanding-widgets-the-core-of-flutter-ui",
    title: "Understanding Widgets: The Core of Flutter UI",
    description: "Dive deep into the fundamental building blocks of Flutter. A look at Stateless vs. Stateful widgets and how to compose beautiful UIs.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-2-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-2-thumbnail")!.imageHint,
    date: "July 25, 2024",
    author: "Reyad",
  },
  {
    id: "blog-3",
    slug: "mastering-layout-in-flutter-rows-columns-and-stacks",
    title: "Mastering Layout in Flutter: Rows, Columns, and Stacks",
    description: "Learn how to arrange widgets and build complex, responsive layouts with Flutter's core layout widgets.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-3-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-3-thumbnail")!.imageHint,
    date: "July 22, 2024",
    author: "Reyad",
  },
  {
    id: "blog-4",
    slug: "a-guide-to-navigation-in-flutter-with-gorouter",
    title: "A Guide to Navigation in Flutter with GoRouter",
    description: "Simplify your app's navigation structure with GoRouter. A practical guide to setting up routes, handling parameters, and nested navigation.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-4-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-4-thumbnail")!.imageHint,
    date: "July 18, 2024",
    author: "Reyad",
  },
  {
    id: "blog-5",
    slug: "state-management-in-flutter-with-riverpod",
    title: "State Management in Flutter with Riverpod",
    description: "A comprehensive guide to leveraging Riverpod for scalable and maintainable state management in your Flutter applications.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-5-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-5-thumbnail")!.imageHint,
    date: "July 15, 2024",
    author: "Reyad",
  },
  {
    id: "blog-6",
    slug: "integrating-firebase-authentication-in-flutter",
    title: "Integrating Firebase Authentication in Your Flutter App",
    description: "Step-by-step tutorial on adding Firebase Authentication for secure user sign-up, sign-in, and session management.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-6-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-6-thumbnail")!.imageHint,
    date: "July 11, 2024",
    author: "Reyad",
  },
  {
    id: "blog-7",
    slug: "using-firestore-with-flutter-for-real-time-data",
    title: "Using Cloud Firestore with Flutter for Real-time Data",
    description: "Learn how to connect your Flutter app to Firestore, perform CRUD operations, and listen to real-time data streams.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-7-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-7-thumbnail")!.imageHint,
    date: "July 08, 2024",
    author: "Reyad",
  },
  {
    id: "blog-8",
    slug: "creating-custom-animations-with-flutter",
    title: "Creating Custom Animations with Flutter's AnimationController",
    description: "Unlock the power of custom animations in Flutter. Learn how to use AnimationController and Tweens to bring your UI to life.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-8-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-8-thumbnail")!.imageHint,
    date: "July 04, 2024",
    author: "Reyad",
  },
  {
    id: "blog-9",
    slug: "theming-your-flutter-app-light-and-dark-modes",
    title: "Theming Your Flutter App: Light and Dark Modes",
    description: "A practical guide to implementing a dynamic theming system in your app, allowing users to switch between light and dark modes.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-9-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-9-thumbnail")!.imageHint,
    date: "June 30, 2024",
    author: "Reyad",
  },
  {
    id: "blog-10",
    slug: "making-http-requests-in-flutter-a-guide-to-the-http-package",
    title: "Making HTTP Requests in Flutter: A Guide to the `http` Package",
    description: "Fetch data from the internet by making GET, POST, PUT, and DELETE requests from your Flutter application.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-10-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-10-thumbnail")!.imageHint,
    date: "June 25, 2024",
    author: "Reyad",
  },
  {
    id: "blog-11",
    slug: "handling-user-input-with-flutter-forms",
    title: "Handling User Input with Flutter Forms",
    description: "A deep dive into creating forms, validating input, and handling submission with Form and TextFormField widgets.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-11-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-11-thumbnail")!.imageHint,
    date: "June 20, 2024",
    author: "Reyad",
  },
  {
    id: "blog-12",
    slug: "local-storage-options-in-flutter-shared-preferences",
    title: "Local Storage Options in Flutter: A Look at shared_preferences",
    description: "Persist simple key-value data on the device using the shared_preferences package for settings, session tokens, and more.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-12-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-12-thumbnail")!.imageHint,
    date: "June 15, 2024",
    author: "Reyad",
  },
  {
    id: "blog-13",
    slug: "flutter-performance-tips-for-a-smooth-60-fps",
    title: "Flutter Performance Tips for a Smooth 60 FPS",
    description: "Optimize your app's performance by understanding build methods, using const widgets, and reducing widget rebuilds.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-13-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-13-thumbnail")!.imageHint,
    date: "June 10, 2024",
    author: "Reyad",
  },
  {
    id: "blog-14",
    slug: "unit-and-widget-testing-in-flutter",
    title: "Unit and Widget Testing in Flutter",
    description: "Ensure your app's reliability with a solid testing strategy. Learn how to write effective unit tests and widget tests.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-14-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-14-thumbnail")!.imageHint,
    date: "June 05, 2024",
    author: "Reyad",
  },
  {
    id: "blog-15",
    slug: "deploying-your-flutter-app-to-the-play-store-and-app-store",
    title: "Deploying Your Flutter App to the Play Store and App Store",
    description: "The final step: a checklist for preparing your app for release, generating builds, and submitting to the official app stores.",
    imageUrl: PlaceHolderImages.find((p) => p.id === "blog-15-thumbnail")!.imageUrl,
    imageHint: PlaceHolderImages.find((p) => p.id === "blog-15-thumbnail")!.imageHint,
    date: "May 30, 2024",
    author: "Reyad",
  },
];
