"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Project } from "@/lib/types";
import { Github, Link as LinkIcon, Bot, Loader2 } from "lucide-react";
import { generateProjectSummaryAction } from "../actions";
import { useToast } from "@/hooks/use-toast";

export function ProjectCard({ project: initialProject }: { project: Project }) {
  const [project, setProject] = useState(initialProject);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleGenerateSummary = async (
    event: React.FormEvent<HTMLFormElement>
  ) => {
    event.preventDefault();
    if (!project.repoLink) return;

    setIsLoading(true);
    const result = await generateProjectSummaryAction(project.repoLink);
    setIsLoading(false);

    if (result.success && result.summary) {
      setProject({ ...project, description: result.summary });
      toast({
        title: "Summary Generated",
        description: "The project summary has been successfully generated by AI.",
      });
    } else {
      toast({
        variant: "destructive",
        title: "Error",
        description: result.error || "An unknown error occurred.",
      });
    }
  };

  return (
    <Card className="flex flex-col">
      <CardHeader>
        <div className="aspect-[3/2] relative overflow-hidden rounded-t-lg">
          <Image
            src={project.imageUrl}
            alt={project.title}
            fill
            className="object-cover"
            data-ai-hint={project.imageHint}
          />
        </div>
      </CardHeader>
      <CardContent className="flex-grow">
        <CardTitle className="mb-2 font-headline">{project.title}</CardTitle>
        <div className="flex flex-wrap gap-2 mb-4">
          {project.tags.map((tag) => (
            <Badge key={tag} variant="secondary">
              {tag}
            </Badge>
          ))}
        </div>
        <p className="text-muted-foreground text-sm min-h-[60px]">
          {project.description}
        </p>
        {!project.description && project.repoLink && (
          <form
            onSubmit={handleGenerateSummary}
            className="mt-4 p-4 border rounded-lg bg-muted/50"
          >
            <p className="text-sm font-medium mb-2 flex items-center gap-2">
              <Bot className="w-4 h-4 text-primary" />
              Generate Summary with AI
            </p>
            <div className="flex gap-2">
              <Input
                type="text"
                defaultValue={project.repoLink}
                className="bg-background"
                readOnly
              />
              <Button type="submit" size="icon" disabled={isLoading}>
                {isLoading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Bot className="h-4 w-4" />
                )}
              </Button>
            </div>
          </form>
        )}
      </CardContent>
      <CardFooter className="flex justify-end gap-2">
        {project.repoLink && (
          <Button variant="outline" size="sm" asChild>
            <Link href={project.repoLink} target="_blank">
              <Github className="mr-2 h-4 w-4" />
              GitHub
            </Link>
          </Button>
        )}
        {project.liveLink && (
          <Button size="sm" asChild>
            <Link href={project.liveLink} target="_blank">
              <LinkIcon className="mr-2 h-4 w-4" />
              Live Demo
            </Link>
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}
